//
// Created by Shiva Shankar patel psy on 12/8/20.
//
///INCLUDE ONLY IN UI.H
#ifndef PHOTOFX_UISHADERCONSTANTS_H
#define PHOTOFX_UISHADERCONSTANTS_H
#include "Graphics.h"

GLint DRAWTYPELOC=0,PARAMSLOC=1,PARAM2LOC=2,PARAM3LOC=4,SAMPLERARRAYLOC=7;
GLint IMAGEVIEWDRAWTYPE=0,IMAGEVIEWSTACKDRAWTYPE=1,SLIDERSETDRAWTYPE=2;
GLint POSITIONATTRIBLOC=0,TEXTCOODATTRIBLOC=2;
#endif //PHOTOFX_UISHADERCONSTANTS_H
